### ISSUE TITLE
Uploading Code not Quite working :(

### ISSUE THREAD

**Issue by BobSaidHi** [x64-bit/6506-Code-2019-v2#1]

**Comment by BobSaidHi** [comment]
I think tyring this wouild work:

1. Clone repo with GitHub Deskotp
2.  Copy Code Over into folder
3. Move anythin that should not be in teh repo to trash
4. verify that the effected fiels are still in teh orginsal direcotry
5.  Comit to to Git.
6. Push to remote repo

**Comment by x64-bit** [comment]
oof

**Comment by BobSaidHi** [comment]
Yah!
